CREATE TABLE IF NOT EXISTS settings (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TEXT NOT NULL,
    kind TEXT NOT NULL,
    trigger TEXT,
    portion TEXT,
    status TEXT NOT NULL,
    message TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS events_kind_id_idx ON events (kind, id DESC);

CREATE TABLE IF NOT EXISTS executions (
    key TEXT PRIMARY KEY
);
